apiVersion: v1
kind: Service
metadata:
  name: webui-mailhog
spec:
  selector:
    app: mailhog
  type: NodePort
  ports:
  - name: http
    port: 8025
    targetPort: 8025
    nodePort: 31825
  - name: smtp
    port: 1025
    targetPort: 1025
    nodePort: 31125
  